name: Build Tauri App

on:
  push:
    tags:
      - 'v*'          # 只有打了 v1.0.0 这种 tag 时才触发

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''
          #- platform: 'macos-latest'
          #  args: '--target universal-apple-darwin'   # 构建 Intel + Apple Silicon 通用包

    runs-on: ${{ matrix.platform }}

    steps:
      # 1. 拉代码
      - uses: actions/checkout@v4

      # 2. 装 Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'   # 如果用 yarn/pnpm，把 npm 换成 yarn/pnpm

      # 3. 装 Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ contains(matrix.platform, 'macos') && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      # 4. 装系统依赖（Linux 才需要）
      - name: Install Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      # 5. 前端依赖 & 构建
      - name: Install frontend deps
        run: npm ci

      # 6. 直接构建
      - name: Build Tauri App
        run: tauri build

      # 7. 发布 linux
      - name: Upload artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: dragon-sweeper-app
          path: ./src-tauri/target/release/app

      # 8. 发布 Windows
      - name: Upload artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: dragon-sweeper-app
          path: ./src-tauri/target/release/app.exe

      # 6. Tauri 官方 Action：构建 + 打包
      #- name: Build Tauri App
      #  uses: tauri-apps/tauri-action@v0
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     #   with:
      #    tagName: ${{ github.ref_name }}
      #    releaseName: "App v${{ github.ref_name }}"
      #    releaseBody: "See the assets to download and install this version."
      #    releaseDraft: false
      #    prerelease: false
      #    args: ${{ matrix.args }}
